feedback/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from feedback import views

urlpatterns = patterns('',

    url(r'^$', views.index, name='feedback'),
    url(r'^success/$', views.success, name='feedback_success'),
)

narayana/urls.py
from django.conf.urls import patterns, include, url
#from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib import admin
from cms.sitemaps import CMSSitemap
from django.utils.functional import curry
from django.views.defaults import server_error, page_not_found, permission_denied
from django.conf.urls.static import static

admin.autodiscover()

handler500 = curry(server_error, template_name='500.html')
handler404 = curry(page_not_found, template_name='404.html')
handler403 = curry(permission_denied, template_name='403.html')

urlpatterns = patterns('',
                       #url(r'^captcha/', include('captcha.urls')),
                       url(r'^tinymce/', include('tinymce.urls')),
                       url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                           {'sitemaps': {'cmspages': CMSSitemap}}),
                       url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns('',
    # список новостей
    url(r'^$', views.news_list, name='news_list'),
    url(r'^page/(?P<page>[1-9]\d*)/$', views.news_list, name='news_list'),
    # новость детально
    url(r'^(?P<news_id>[1-9]\d*)/$', views.news_detail, name='news_detail'),
)

feedback/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
from tinymce import models as tinymce_models
from django.forms import ValidationError


class MailTemplate(models.Model):
    title = models.CharField(u'Название', max_length=255)
    code = models.CharField(u'Символьный код', max_length=255, unique=True)
    from_name = models.CharField(u'От (имя)', max_length=255)
    from_email = models.EmailField(u'От (e-mail)', max_length=255)
    admin_email = models.EmailField(u'Кому (e-mail)', max_length=255)
    copy_emails = models.EmailField(u'Копия (e-mail)', max_length=255, blank=True)
    subject = models.CharField(u'Тема сообщения', max_length=255)
    body = tinymce_models.HTMLField(u'Текст сообщения', blank=True)

    class Meta:
        verbose_name = u'почтовый шаблон'
        verbose_name_plural = u'почтовые шаблоны'
        ordering = ['id']

    def __unicode__(self):
        return self.title


class FeedbackSubject(models.Model):
    title = models.CharField(u'Тема', max_length=255)
    is_active = models.BooleanField(u'Активность', default=True)

    class Meta:
        verbose_name = u'тема обращения'
        verbose_name_plural = u'темы обращений'
        ordering = ['id']

    def __unicode__(self):
        return self.title


class Feedback(models.Model):
    user_name = models.CharField(u'Имя пользователя', max_length=255)
    subject = models.ForeignKey(FeedbackSubject, verbose_name=u'Тема', limit_choices_to={'is_active':True})
    email = models.EmailField(u'E-mail')
    body = models.TextField(u'Текст обращения')
    is_answer_needed = models.BooleanField(u'Требует ответа', default=False, blank=True)
    create_date = models.DateTimeField(u'Дата создания', default=datetime.datetime.now())

    class Meta:
        verbose_name = u'обращение пользователя'
        verbose_name_plural = u'обращения пользователей'
        ordering = ['-create_date', '-id']

    def __unicode__(self):
        return self.body

feedback/forms.py
# -*- coding: utf-8 -*-
from feedback.models import Feedback, FeedbackSubject
from django import forms
from captcha.fields import CaptchaField


class FeedbackForm(forms.ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = Feedback
        exclude = ['create_date']
        #fields = ['active_subjects', 'body', 'email']

feedback/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from feedback.forms import FeedbackForm
from feedback.models import MailTemplate
from django.core.mail import EmailMessage
from django.contrib import messages
import datetime
from django.utils.translation import ugettext as _


def index(request):

    if request.method == 'POST':

        f = FeedbackForm(data=request.POST)
        if f.is_valid():
            f.instance.create_date = datetime.datetime.now()
            f.save()

            mail_template = MailTemplate.objects.get(code__exact='FEEDBACK')
            body = mail_template.body.replace('###hostname###', request.get_host())
            body = body.replace('###email###', f.instance.email)
            body = body.replace('###user_name###', f.instance.user_name)
            body = body.replace('###subject###', f.instance.subject.title)
            body = body.replace('###body###', f.instance.body)
            body = body.replace('###is_answer_needed###', u'Да' if f.instance.is_answer_needed else u'Нет')

            email = EmailMessage(
                mail_template.subject,
                body,
                mail_template.from_email,
                [mail_template.admin_email, ],
                [mail_template.copy_emails, ],
                headers={'Reply-To': mail_template.from_email, 'From': mail_template.from_name}
            )

            email.content_subtype = "html"
            email.send()
            messages.add_message(request, messages.SUCCESS, _("Message sent successfully!"))
            return redirect('feedback_success')

    else:
        f = FeedbackForm()

    return render(request, 'feedback/index.html', {'form': f})


def success(request):
    return render(request, 'feedback/success.html')

feedback/templates/feedback/index.html
{% extends "inner.html" %}
{% load i18n %}
{% block content %}
<div id="feedback">
      <div class="block">
        <h1>{% trans "Feedback" %}</h1>
            <form class="feedback" action="." method="post">
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
             <div class="feedback__row {% if form.subject.errors %}has-error{% endif %}">
                <div class="feedback__label _subject-opener">
                 <label for="id_subject">{% trans "Subject:" %}</label>
                </div>
                <div class="feedback__input">
                    {{ form.subject}}
                </div>
             </div>
            {{ form.subject.errors }}

            <div class="feedback__row{% if form.user_name.errors %}has-error{% endif %}">
                 <div class="feedback__label">
                    <label for="id_user_name">{% trans "Name:" %}</label>
                 </div>
                    <div class="feedback__input">
                    {{ form.user_name}}
                </div>
            </div>
            {{ form.user_name.errors }}

                <div class="feedback__row {% if form.email.errors %}has-error{% endif %}">
                   <div class="feedback__label"> <label for="id_email">{% trans "E-mail:" %}</label></div>
                    <div class="feedback__input">{{ form.email }}</div>
                </div>
            {{ form.email.errors }}


            <div class="feedback__row {% if form.body.errors %}has-error{% endif %}">
               <div class="feedback__label"> <label for="id_body">{% trans "Message:" %}</label></div>
                <div class="feedback__input">{{ form.body }}</div>
            </div>
            {{ form.body.errors }}

             <div class="feedback__row {% if form.captcha.errors %}has-error{% endif %}">
               <div class="feedback__label"> <label for="id_captcha">{% trans "Input code:" %}</label></div>
                <div class="feedback__input">
                    {{ form.captcha }}
                    {{ form.captcha.errors }}
                <div class="feedback__reply">
                    <div class="checkbox__reply"></div>{% trans "Need feedback" %}
                </div>
                    <div class="feedback__send">
                        {% csrf_token %}
                        <a href="javascript:void(0)" onclick="this.form.submit()" class="btn">{% trans "Send" %}</a>
                    </div>
                </div>
            </div>
          <input type="hidden" name="is_answer_needed" value="false" id="reply">
        </form>
      </div>
</div>
{% endblock %}

feedback/templates/feedback/success.html
{% extends "inner.html" %}

{% block content %}
<div id="feedback">
      <div class="block">
    {% for message in messages %}
        <div class="alert alert-success">
            <p>{{ message }}</p>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}